from __future__ import annotations

from typing import Any

__version__: str


class SegmenterConfig:
    include_sentences: bool
    min_span_bytes: int

    def __init__(
        self,
        include_sentences: bool = True,
        min_span_bytes: int = 1,
    ) -> None: ...

    @staticmethod
    def default() -> SegmenterConfig: ...


class Segmenter:
    def __init__(self, config: SegmenterConfig | None = None) -> None: ...

    @staticmethod
    def default() -> Segmenter: ...

    @staticmethod
    def from_model_dir(
        model_dir: str,
        config: SegmenterConfig | None = None,
    ) -> Segmenter: ...

    def spans(self, text: str) -> list[dict[str, Any]]: ...
    def annotate(self, text: str) -> dict[str, Any]: ...
    def tagged(self, text: str) -> str: ...
    def benchmark(self, text: str, iterations: int = 10) -> dict[str, Any]: ...


def annotate(text: str) -> dict[str, Any]: ...
def spans(text: str) -> list[dict[str, Any]]: ...
def tagged(text: str) -> str: ...
def render(text: str, spans: list[tuple[str, int, int, float | None]]) -> str: ...
def render_bytes(text: str, spans: list[tuple[str, int, int, float | None]]) -> str: ...
